version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run deps-build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run deps-test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
