version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
      - restore_cache:
        - v1-dependencies-{{ checksum "package.json" }}  
        - v1-dependencies- 
      - run: npm run deps-build
      - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run: 
        name: Testing
        command: npm run deps-test    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
