version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run deps-build
      - run: npm run deps-test    
workflows:
  version: 2
  build:
    jobs:
      - build
