version: 2
jobs:
  build_and_test:  
    working_directory: ~/mn_pita
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: git fetch origin staging
      - run: git rebase staging
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules      
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy_to_master:
    working_directory: ~/mn_pita
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: git fetch origin master
      - run: git rebase master
    - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
    - restore_cache:
        keys:
          - dependency-cache-{{ checksum "package.json" }}
          - dependency-cache-
    - run:
        name: Install npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules      
    - run:
        name: Test
        command: npm test
    - store_artifacts:
        path: test-results.xml
        prefix: tests
    - store_artifacts:
        path: coverage
        prefix: coverage 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
  build_for_master:
    job:
      - deploy_to_master:
        requires:
            - deploy_to_staging
        filters:
            branches:
              only: staging     
