version: 2
jobs:
  build:  
    working_directory: ~/mn_pita
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:latest
    environment:
      - MONGO_URL: "mongodb://localhost:27017"
    steps:
      - checkout
      - run: git fetch origin staging
      - run: git rebase staging
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: |
          docker run -d --name mongodb mongodb
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules      
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build